
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.imageio.ImageIO;
import misFrames.SumaPage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luis2
 */
public class MainFrame extends javax.swing.JFrame {
       
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
        setBounds(50,50,1250,640);
        //this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image logoo= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imgs/Beach+Ball.png"));
        return logoo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        logo = new javax.swing.JLabel();
        FondoNegro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();
        mniniciar = new javax.swing.JMenu();
        mnSuma = new javax.swing.JMenuItem();
        mnModoProdigio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        Escritorio.setLayer(logo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(FondoNegro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(433, 433, 433))
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(FondoNegro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(FondoNegro)
                .addGap(45, 45, 45)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnOpciones.setText("Opciones");

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnOpciones.add(mnSalir);

        jMenuBar1.add(mnOpciones);

        mniniciar.setText("Iniciar");
        mniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniniciarActionPerformed(evt);
            }
        });

        mnSuma.setText("Sumar y Restar");
        mnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSumaActionPerformed(evt);
            }
        });
        mniniciar.add(mnSuma);

        mnModoProdigio.setText("Modo Prodigio");
        mnModoProdigio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnModoProdigioActionPerformed(evt);
            }
        });
        mniniciar.add(mnModoProdigio);

        jMenuBar1.add(mniniciar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniniciarActionPerformed
        //TODO noseque
    }//GEN-LAST:event_mniniciarActionPerformed

    private void mnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSumaActionPerformed
       SumaPage sp = new SumaPage();
        Escritorio.add(sp);
        
        sp.setVisible(true);
        
    }//GEN-LAST:event_mnSumaActionPerformed

    private void mnModoProdigioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnModoProdigioActionPerformed
        SumaPage sp = new SumaPage();
        Escritorio.add(sp);
        
        sp.Activo(true);
       
        sp.setVisible(true);
        
    }//GEN-LAST:event_mnModoProdigioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel FondoNegro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuItem mnModoProdigio;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnSuma;
    private javax.swing.JMenu mniniciar;
    // End of variables declaration//GEN-END:variables
}
