/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misFrames;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import misFrames.misPaneles.PanelResta;
import misFrames.misPaneles.PanelSuma;

/**
 *
 * @author luis2
 */
public class SumaPage extends javax.swing.JInternalFrame {
    GridBagLayout layout = new GridBagLayout();
    int veces = 0;
    
    int AciertosT = 0;
    
    private Timer t;
    //private ActionListener ac;
    int x= 100;//barra tiempo progreso
    
    PanelSuma pS;
    PanelResta pR;
    String div="";
    private boolean cambio;
    private boolean prodigioMode = false;
    
    /**
     * Creates new form SumaPage
     */
    public SumaPage() {
        initComponents();
       
        pS = new PanelSuma();
        pR = new PanelResta();
        PanelDinamico.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx= 0;
        c.gridy = 0;
        PanelDinamico.add(pS,c);
        c.gridx= 0;
        c.gridy = 0;
        PanelDinamico.add(pR,c);
        pS.setVisible(true);
        pR.setVisible(false);
        
        labelTime.setVisible(false);
        barraTime.setVisible(false);
        cuadroTime.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelbtn = new javax.swing.JPanel();
        Btnpanel1 = new javax.swing.JButton();
        Btnpanel2 = new javax.swing.JButton();
        BtnPanel3 = new javax.swing.JButton();
        BtnPanel4 = new javax.swing.JButton();
        BtnPanel5 = new javax.swing.JButton();
        BtnPanel6 = new javax.swing.JButton();
        BtnPanel7 = new javax.swing.JButton();
        BtnPanel8 = new javax.swing.JButton();
        BtnPanel9 = new javax.swing.JButton();
        BtnPanel0 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnResolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logoUv = new javax.swing.JLabel();
        cuadroTime = new javax.swing.JPanel();
        labelTime = new javax.swing.JLabel();
        barraTime = new javax.swing.JProgressBar();
        PanelDinamico = new javax.swing.JPanel();

        setClosable(true);
        setForeground(new java.awt.Color(255, 255, 255));
        setTitle("Suma o Resta las pelotas:");
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1250, 617));

        Panelbtn.setBackground(new java.awt.Color(204, 204, 255));

        Btnpanel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btnpanel1.setText("1");
        Btnpanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnpanel1ActionPerformed(evt);
            }
        });

        Btnpanel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btnpanel2.setText("2");
        Btnpanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnpanel2ActionPerformed(evt);
            }
        });

        BtnPanel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel3.setText("3");
        BtnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel3ActionPerformed(evt);
            }
        });

        BtnPanel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel4.setText("4");
        BtnPanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel4ActionPerformed(evt);
            }
        });

        BtnPanel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel5.setText("5");
        BtnPanel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel5ActionPerformed(evt);
            }
        });

        BtnPanel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel6.setText("6");
        BtnPanel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel6ActionPerformed(evt);
            }
        });

        BtnPanel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel7.setText("7");
        BtnPanel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel7ActionPerformed(evt);
            }
        });

        BtnPanel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel8.setText("8");
        BtnPanel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel8ActionPerformed(evt);
            }
        });

        BtnPanel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel9.setText("9");
        BtnPanel9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel9ActionPerformed(evt);
            }
        });

        BtnPanel0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnPanel0.setText("0");
        BtnPanel0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel0ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        resultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 0, 0));
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultado.setText("?");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnResolver.setText("Comprobar");
        btnResolver.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        logoUv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/uV_LuisAguirre100x100.gif"))); // NOI18N
        logoUv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoUvMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoUv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoUv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cuadroTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelTime.setText("Tiempo:");

        javax.swing.GroupLayout cuadroTimeLayout = new javax.swing.GroupLayout(cuadroTime);
        cuadroTime.setLayout(cuadroTimeLayout);
        cuadroTimeLayout.setHorizontalGroup(
            cuadroTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cuadroTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuadroTimeLayout.createSequentialGroup()
                        .addComponent(labelTime)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(barraTime, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap())
        );
        cuadroTimeLayout.setVerticalGroup(
            cuadroTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(barraTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelbtnLayout = new javax.swing.GroupLayout(Panelbtn);
        Panelbtn.setLayout(PanelbtnLayout);
        PanelbtnLayout.setHorizontalGroup(
            PanelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelbtnLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Btnpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btnpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cuadroTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelbtnLayout.setVerticalGroup(
            PanelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelbtnLayout.createSequentialGroup()
                .addGroup(PanelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelbtnLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Btnpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Btnpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelbtnLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cuadroTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnPanel4.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(Panelbtn, java.awt.BorderLayout.PAGE_END);

        PanelDinamico.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout PanelDinamicoLayout = new javax.swing.GroupLayout(PanelDinamico);
        PanelDinamico.setLayout(PanelDinamicoLayout);
        PanelDinamicoLayout.setHorizontalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1187, Short.MAX_VALUE)
        );
        PanelDinamicoLayout.setVerticalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        getContentPane().add(PanelDinamico, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btnpanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnpanel1ActionPerformed
        Resultado("1");
    }//GEN-LAST:event_Btnpanel1ActionPerformed

    private void BtnPanel0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel0ActionPerformed
        Resultado("0");
    }//GEN-LAST:event_BtnPanel0ActionPerformed

    private void Btnpanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnpanel2ActionPerformed
        Resultado("2");
    }//GEN-LAST:event_Btnpanel2ActionPerformed

    private void BtnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel3ActionPerformed
        Resultado("3");
    }//GEN-LAST:event_BtnPanel3ActionPerformed

    private void BtnPanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel4ActionPerformed
        Resultado("4");
    }//GEN-LAST:event_BtnPanel4ActionPerformed

    private void BtnPanel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel5ActionPerformed
        Resultado("5");
    }//GEN-LAST:event_BtnPanel5ActionPerformed

    private void BtnPanel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel6ActionPerformed
        Resultado("6");
    }//GEN-LAST:event_BtnPanel6ActionPerformed

    private void BtnPanel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel7ActionPerformed
        Resultado("7");
    }//GEN-LAST:event_BtnPanel7ActionPerformed

    private void BtnPanel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel8ActionPerformed
        Resultado("8");
    }//GEN-LAST:event_BtnPanel8ActionPerformed

    private void BtnPanel9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel9ActionPerformed
        Resultado("9");
       
    }//GEN-LAST:event_BtnPanel9ActionPerformed

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        //Valores.get_resultado(div);
       
        if(cambio == false){
           pS.Calculos(div); 
           this.x = this.x + pS.addtiempo;
           AciertosT = pS.aciertosS + pR.aciertosR;
           /* if (AciertosT == 3){
               this.prodigioMode = true;
            }
            if (this.prodigioMode == true){
                modoProdigio();
                this.prodigioMode = false;
            }*/
           
           pS.setVisible(false);
           pR.setVisible(true);
           this.setBounds(0,0,1250,617);
           cambio = true;
           
       }else{
           pR.Calculos2(div);
           this.x = this.x + pR.addTiempo;
           
           AciertosT = pS.aciertosS + pR.aciertosR;
           /* if (AciertosT == 4){
                this.prodigioMode = true;
            }
            if (this.prodigioMode == true){
                modoProdigio();
                this.prodigioMode = false;
            }*/
            
           pR.setVisible(false); 
           pS.setVisible(true);
           this.setBounds(0,0,1250,617);
           cambio= false;
          
       }
            this.div ="";
            resultado.setText("");
       
        
    }//GEN-LAST:event_btnResolverActionPerformed

    public void Activo(boolean Act){
        
        if( Act == true){
            modoProdigio();
            System.out.println("activado");
        }
    }
    
    private void modoProdigio(){
        this.x= 100;
        JOptionPane.showMessageDialog(null, 
                        "Has activado el Modo prodigio!\nAhora tendras tiempo\n¿Cuántos aciertos lograrás?" ,
                        "M O D O     P R O D I G I O", JOptionPane.PLAIN_MESSAGE, 
                        null);
        labelTime.setVisible(true);
        barraTime.setVisible(true);
        cuadroTime.setVisible(true);
         t = new Timer( 150, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                x = x - 1;
                barraTime.setValue(x);
                if(barraTime.getValue()== 0){
                    JOptionPane.showMessageDialog(null,
                                            "Lograste "+ (AciertosT) +" acierto(s)!",
                                            "Se acabó el tiempo",JOptionPane.PLAIN_MESSAGE,
                                            null);
                    dispose();
                    t.stop();
                }
            }
        });
        t.start();
    }
    private void logoUvMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoUvMouseReleased
        IconoTeam equipo = new IconoTeam();
        
        veces++;
        if(veces > 3){
            JOptionPane.showMessageDialog(null, 
                    "Creado por: Eduardo Aguirre\n"
                    + "Idea y Concepto: Felipe Ramirez\n"
                    + "Imágenes y Boceto: Bryan Chiz", 
                    "Créditos", 
                    JOptionPane.DEFAULT_OPTION,
                    equipo);
        veces = 0;
        }
    }//GEN-LAST:event_logoUvMouseReleased

     public void Resultado(String valor){
         div = valor;
         resultado.setText(div); //resultado es el nombre del label del frame daah
         
     }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPanel0;
    private javax.swing.JButton BtnPanel3;
    private javax.swing.JButton BtnPanel4;
    private javax.swing.JButton BtnPanel5;
    private javax.swing.JButton BtnPanel6;
    private javax.swing.JButton BtnPanel7;
    private javax.swing.JButton BtnPanel8;
    private javax.swing.JButton BtnPanel9;
    private javax.swing.JButton Btnpanel1;
    private javax.swing.JButton Btnpanel2;
    private javax.swing.JPanel PanelDinamico;
    private javax.swing.JPanel Panelbtn;
    private javax.swing.JProgressBar barraTime;
    private javax.swing.JButton btnResolver;
    private javax.swing.JPanel cuadroTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel logoUv;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
